// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPLiFWkZX4emp7meocGCX0X0Fn16hMX60',
    appId: '1:502090485540:web:49ce111795db30072dadb1',
    messagingSenderId: '502090485540',
    projectId: 'gangksdaweq2',
    authDomain: 'gangksdaweq2.firebaseapp.com',
    storageBucket: 'gangksdaweq2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32GLAOPsyihaobwxPvBZjsjDhcWy-Uds',
    appId: '1:502090485540:android:5cf3de8b351392942dadb1',
    messagingSenderId: '502090485540',
    projectId: 'gangksdaweq2',
    storageBucket: 'gangksdaweq2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbhzfLsVj5WxjInrUztiQCjMqsNl-z-k',
    appId: '1:502090485540:ios:5372712d3daf29692dadb1',
    messagingSenderId: '502090485540',
    projectId: 'gangksdaweq2',
    storageBucket: 'gangksdaweq2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYbhzfLsVj5WxjInrUztiQCjMqsNl-z-k',
    appId: '1:502090485540:ios:5372712d3daf29692dadb1',
    messagingSenderId: '502090485540',
    projectId: 'gangksdaweq2',
    storageBucket: 'gangksdaweq2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPLiFWkZX4emp7meocGCX0X0Fn16hMX60',
    appId: '1:502090485540:web:7b0297f02e705e792dadb1',
    messagingSenderId: '502090485540',
    projectId: 'gangksdaweq2',
    authDomain: 'gangksdaweq2.firebaseapp.com',
    storageBucket: 'gangksdaweq2.firebasestorage.app',
  );
}
